[project]
name = "fredrikaverpil-github-com"
version = "0.1.0"
description = "Personal website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "zensical",
  "pillow",
  "cairosvg",
]
